# Generated by Django 5.2 on 2025-05-26 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Topshiriq berildi'), ('accepted', 'Qabul qilindi'), ('in_progress', 'Bajarilmoqda'), ('submitted', 'Tasdiqlashga yuborilgan'), ('approved', 'Tasdiqlandi'), ('expired', 'Bajarilmadi'), ('returned', 'Qayta ishlashga yuborildi')], max_length=50)),
                ('received', models.DateField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('degree', models.CharField(choices=[('info', "Ma'lumot uchun"), ('medium', 'Ahamiyatli'), ('important', 'Muhim'), ('very_important', 'Juda muhim'), ('urgent', 'Tezkor')], default='medium', max_length=50)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='profiles.profile')),
                ('performers', models.ManyToManyField(related_name='performers', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DeadlineExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('requested_deadline', models.DateTimeField(blank=True, null=True)),
                ('accepted_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Bekor qilindi')], default='in_progress', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_requests_made', to='profiles.profile')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadline_requests_responded', to='profiles.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_extension_requests', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/answer_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
        ),
    ]
